### ISSUE TITLE
Explodes with spawn E2BIG

### ISSUE THREAD

**Issue by i-am-the-slime** [kaiyote/electron-purs-boilerplate#2]
After doing `yarn`:
```
yarn install v0.27.5
[1/5] Resolving packages...
[2/5] Fetching packages...
[3/5] Linking dependencies...
[4/5] Building fresh packages...
[5/5] Cleaning modules...
$ bower install
error An unexpected error occurred: "spawn E2BIG".
```
What can I do?

**Comment by i-am-the-slime** [comment]
Seems like it works with `npm run dev`.

**Comment by kaiyote** [comment]
Are you on macOS? I know i've seen it there, but never really went too deep trying to figure out why. You're correct that `npm run dev` works, and is actually just what I do on mac.

**Comment by i-am-the-slime** [comment]
Yes I am. So I'll just try that then 👍

**Comment by kaiyote** [comment]
Tried to do some research on this in what little time I have. From what I can tell it's specific to macOS and maybe Linux to a lesser extent, and E2BIG is specifically complaining about the length of the arguments list being too large (there's apparently some magic var somewhere that controls it). Apparently yarn does something different than npm does re: that, but I have no idea what that difference is, or how to convince yarn to behave itself (or maybe its npm that's just ignoring things and continuing on its merry way.)

Either way, I'll at least update the README to point out that `yarn dev` may be problematic on macOS and that `npm run dev` can be used instead.
